### ISSUE TITLE
Thread: main, Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://weibo.com/myeslpod (has extras)

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#103]
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140126%26_u.date01%3D20140131%26explorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.appVersion%3A1.5.1c/

version: 1.5.1c
os: 2.3.5

Thread: main, Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://weibo.com/myeslpod (has extras) }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1449)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
 at android.app.Activity.startActivityForResult(Activity.java:2873)
 at android.app.Activity.startActivity(Activity.java:2979)
 at android.text.style.URLSpan.onClick(URLSpan.java:93)
 at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:247)
 at android.widget.TextView.onTouchEvent(TextView.java:7961)
 at android.view.View.dispatchTouchEvent(View.java:3935)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1740)
 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1171)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2132)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1724)
 at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2241)
 at android.view.ViewRoot.handleMessage(ViewRoot.java:1925)
 at android.os.Handler.dispatchMessage(Handler.java:130)
 at android.os.Looper.loop(SourceFile:351)
 at android.app.ActivityThread.main(ActivityThread.java:3814)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:538)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:659)
 at dalvik.system.NativeStart.main(Native Method)

 Thread: main, Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=http://weibo.com/myeslpod (has extras) }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1449)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
 at android.app.Activity.startActivityForResult(Activity.java:2873)
 at android.app.Activity.startActivity(Activity.java:2979)
 at android.text.style.URLSpan.onClick(URLSpan.java:93)
 at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:247)
 at android.widget.TextView.onTouchEvent(TextView.java:7961)
 at android.view.View.dispatchTouchEvent(View.java:3935)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:973)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1740)
 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1171)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2132)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1724)
 at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2241)
 at android.view.ViewRoot.handleMessage(ViewRoot.java:1925)
 at android.os.Handler.dispatchMessage(Handler.java:130)
 at android.os.Looper.loop(SourceFile:351)
 at android.app.ActivityThread.main(ActivityThread.java:3814)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:538)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:659)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
not reproduce
