### ISSUE TITLE
Exception: java.lang.RuntimeException: Error receiving broadcast Intent  android.intent.action.DOWNLOAD_COMPLETE

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#117]
ver: 1.5.1c
os: 4.2.1
moblie: (not set)
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140226%26_u.date01%3D20140226%26_r.drilldown%3Danalytics.appVersion%3A1.5.1c%26explorer-table.plotKeys%3D%5B%5D/

Thread: main, Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.lw1a2.myeslpod (has extras) } in com.lw1a2.myeslpod.bn@43137d50
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:780)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5083)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
 at dalvik.system.NativeStart.main(Native Method) Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE typ=application/vnd.android.package-archive flg=0x10000000 }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1690)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1436)
 at android.app.Activity.startActivityForResult(Activity.java:3433)
 at android.app.Activity.startActivityForResult(Activity.java:3394)
 at android.app.Activity.startActivity(Activity.java:3629)
 at android.app.Activity.startActivity(Activity.java:3597)
 at com.lw1a2.myeslpod.bn.e(Unknown Source)
 at com.lw1a2.myeslpod.bn.onReceive(Unknown Source)
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:770) ... 9 more

Thread: main, Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.lw1a2.myeslpod (has extras) } in com.lw1a2.myeslpod.bn@43137d50
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:780)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5083)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
 at dalvik.system.NativeStart.main(Native Method) Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE typ=application/vnd.android.package-archive flg=0x10000000 }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1690)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1436)
 at android.app.Activity.startActivityForResult(Activity.java:3433)
 at android.app.Activity.startActivityForResult(Activity.java:3394)
 at android.app.Activity.startActivity(Activity.java:3629)
 at android.app.Activity.startActivity(Activity.java:3597)
 at com.lw1a2.myeslpod.Upgrade.install(Unknown Source)
                               access$5
 at com.lw1a2.myeslpod.Upgrade.onReceive(Unknown Source)
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:770) ... 9 more

**Comment by lw1a2** [comment]
ver: 1.5.1c
os: 4.2.2
moblie: Lenovo K910L Vibe Z
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140227%26_u.date01%3D20140227%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo%26_r.drilldown%3Danalytics.appVersion%3A1.5.1c/

Thread: main, Exception: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.lw1a2.myeslpod (has extras) } in com.lw1a2.myeslpod.bn@412c78d8
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:768)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5138)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
 at dalvik.system.NativeStart.main(Native Method) Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.INSTALL_PACKAGE dat=file:///storage/emulated/0/Download/MyEslPod.apk typ=application/vnd.android.package-archive flg=0x10000000 }
 at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1622)
 at android.app.Instrumentation.execStartActivity(Instrumentation.java:1417)
 at android.app.Activity.startActivityForResult(Activity.java:3370)
 at android.app.Activity.startActivityForResult(Activity.java:3331)
 at android.app.Activity.startActivity(Activity.java:3566)
 at android.app.Activity.startActivity(Activity.java:3534)
 at com.lw1a2.myeslpod.bn.e(Unknown Source)
 at com.lw1a2.myeslpod.bn.onReceive(Unknown Source)
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:758) ... 9 more
