### ISSUE TITLE
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification.

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#123]
ver: 1.6
os: 4.4.2
mobile: Google Nexus 7

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140305%26_u.date01%3D20140306%26explorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.appVersion%3A1.6/

Thread: main, Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131427356, class android.widget.ListView) with Adapter(class com.lw1a2.myeslpod.ae)]
 at android.widget.ListView.layoutChildren(ListView.java:1555)
 at android.widget.AbsListView.onTouchUp(AbsListView.java:3617)
 at android.widget.AbsListView.onTouchEvent(AbsListView.java:3429)
 at android.view.View.dispatchTouchEvent(View.java:7706)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
 at android.view.View.dispatchPointerEvent(View.java:7886)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:138)
 at android.os.Looper.loop(Looper.java:123)
 at android.app.ActivityThread.main(ActivityThread.java:5017)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131427356, class android.widget.ListView) with Adapter(class com.lw1a2.myeslpod.ae)]
 at android.widget.ListView.layoutChildren(ListView.java:1555)
 at android.widget.AbsListView.onTouchUp(AbsListView.java:3617)
 at android.widget.AbsListView.onTouchEvent(AbsListView.java:3429)
 at android.view.View.dispatchTouchEvent(View.java:7706)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2458)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
 at android.view.View.dispatchPointerEvent(View.java:7886)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:138)
 at android.os.Looper.loop(Looper.java:123)
 at android.app.ActivityThread.main(ActivityThread.java:5017)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
ver: 1.6.3c
os: 4.4.2
mobile: Google Nexus 4

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140326%26_u.date01%3D20140326%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D[]%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: main, Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558431, class android.widget.ListView) with Adapter(class com.lw1a2.myeslpod.ai)]
 at android.widget.ListView.layoutChildren(ListView.java:1555)
 at android.widget.AbsListView.onTouchUp(AbsListView.java:3619)
 at android.widget.AbsListView.onTouchEvent(AbsListView.java:3431)
 at android.view.View.dispatchTouchEvent(View.java:7713)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2468)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
 at android.view.View.dispatchPointerEvent(View.java:7893)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:138)
 at android.os.Looper.loop(Looper.java:123)
 at android.app.ActivityThread.main(ActivityThread.java:5050)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131558431, class android.widget.ListView) with Adapter(class com.lw1a2.myeslpod.ai)]
 at android.widget.ListView.layoutChildren(ListView.java:1555)
 at android.widget.AbsListView.onTouchUp(AbsListView.java:3619)
 at android.widget.AbsListView.onTouchEvent(AbsListView.java:3431)
 at android.view.View.dispatchTouchEvent(View.java:7713)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2210)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1945)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
 at android.app.Activity.dispatchTouchEvent(Activity.java:2468)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
 at android.view.View.dispatchPointerEvent(View.java:7893)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3954)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3833)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3525)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3582)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3449)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3418)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3426)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3399)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5602)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5582)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5553)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5682)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:138)
 at android.os.Looper.loop(Looper.java:123)
 at android.app.ActivityThread.main(ActivityThread.java:5050)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:791)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
not reproduce in 1.7.2
