### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#137]
version: 1.6.3c
os: 4.1.1
mobile: Lenovo S890
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140331%26_u.date01%3D20140331%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D/

Thread: main, Exception: java.lang.ArrayIndexOutOfBoundsException: length=500; index=907
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:168)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
 at android.text.StaticLayout.generate(StaticLayout.java:281)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
 at android.text.DynamicLayout.<init>(DynamicLayout.java:170)
 at android.widget.TextView.makeSingleLayout(TextView.java:5999)
 at android.widget.TextView.makeNewLayout(TextView.java:5897)
 at android.widget.TextView.onMeasure(TextView.java:6254)
 at android.view.View.measure(View.java:15282)
 at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1196)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.widget.ScrollView.onMeasure(ScrollView.java:318)
 at android.view.View.measure(View.java:15282)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15282)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15282)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15282)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.view.View.measure(View.java:15282)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15282)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4916)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2166)
 at android.view.View.measure(View.java:15282)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2129)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1240)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1433)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4607)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:753)
 at android.view.Choreographer.doCallbacks(Choreographer.java:573)
 at android.view.Choreographer.doFrame(Choreographer.java:539)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:739)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:153)
 at android.app.ActivityThread.main(ActivityThread.java:5108)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:989)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
version: 1.7c
os: 4.1.2
mobile: Samsung GT-I9268 Galaxy Premier
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140403%26_u.date01%3D20140404%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo%26_r.drilldown%3Danalytics.appVersion%3A1.7c/

Thread: main, Exception: java.lang.IndexOutOfBoundsException
at android.graphics.Paint.getTextRunAdvances(Paint.java:1774)
at android.graphics.Paint.getTextRunAdvances(Paint.java:1747)
at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
at android.text.StaticLayout.generate(StaticLayout.java:281)
at android.text.DynamicLayout.reflow(DynamicLayout.java:332)
at android.text.DynamicLayout.(DynamicLayout.java:176)
at android.widget.TextView.makeSingleLayout(TextView.java:6166)
at android.widget.TextView.makeNewLayout(TextView.java:6064)
at android.widget.TextView.onMeasure(TextView.java:6423)
at android.view.View.measure(View.java:15504)
at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1462)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.widget.ScrollView.onMeasure(ScrollView.java:388)
at android.view.View.measure(View.java:15504)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
at android.view.View.measure(View.java:15504)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
at android.view.View.measure(View.java:15504)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
at android.view.View.measure(View.java:15504)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at android.view.View.measure(View.java:15504)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
at android.view.View.measure(View.java:15504)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4827)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2375)
at android.view.View.measure(View.java:15504)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1971)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1214)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1387)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4474)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
at android.view.Choreographer.doCallbacks(Choreographer.java:555)
at android.view.Choreographer.doFrame(Choreographer.java:525)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4918)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
It should be a system bug:
http://stackoverflow.com/questions/12849676/i-cant-figure-the-issue-with-a-stacktrace-error
