### ISSUE TITLE
java.lang.NullPointerException DownloadManager.enqueue

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#139]
version: 1.6.3c
os: 4.1.1
mobile: (not set)
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140401%26_u.date01%3D20140401%26explorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.appVersion%3A1.6.3c/

Thread: main, Exception: java.lang.NullPointerException
 at android.app.DownloadManager.enqueue(DownloadManager.java)
 at com.lw1a2.myeslpod.ch.d(Unknown Source)
 at com.lw1a2.myeslpod.ch.l(Unknown Source)
 at com.lw1a2.myeslpod.cm.onClick(Unknown Source)
 at android.view.View.performClick(View.java)
 at android.view.View$PerformClick.run(View.java)
 at android.os.Handler.handleCallback(Handler.java)
 at android.os.Handler.dispatchMessage(Handler.java)
 at android.os.Looper.loop(Looper.java)
 at android.app.ActivityThread.main(ActivityThread.java)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.NullPointerException
 at android.app.DownloadManager.enqueue(DownloadManager.java)
 at com.lw1a2.myeslpod.Upgrade.downloadApk(Unknown Source)
 at com.lw1a2.myeslpod.Upgrade.access$18(Unknown Source)
 at com.lw1a2.myeslpod.Upgrade$4$1.onClick(Unknown Source)
 at android.view.View.performClick(View.java)
 at android.view.View$PerformClick.run(View.java)
 at android.os.Handler.handleCallback(Handler.java)
 at android.os.Handler.dispatchMessage(Handler.java)
 at android.os.Looper.loop(Looper.java)
 at android.app.ActivityThread.main(ActivityThread.java)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
It doesn't happened in latest version (1.9)
