### ISSUE TITLE
java.lang.NullPointerException DownloadInfo.downloadInfoImpl

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#144]
version: 1.7.1
os: 4.4.2
mobile: LG Nexus 5

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140416%26_u.date01%3D20140417%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D/

Thread: Thread-16248, Exception: java.lang.NullPointerException
 at com.lw1a2.myeslpod.ae.a(Unknown Source)
 at com.lw1a2.myeslpod.ae.run(Unknown Source)

Thread: Thread-16248, Exception: java.lang.NullPointerException
 at com.lw1a2.myeslpod.Download$DownloadInfo.downloadInfoImpl(Unknown Source)
 at com.lw1a2.myeslpod.Download$DownloadInfo.run(Unknown Source)

**Comment by lw1a2** [comment]
It doesn't happened in latest version (1.9)
