### ISSUE TITLE
android.view.WindowManager$BadTokenException:

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#145]
version: 1.7.1c
os: 4.1.2
mobile: Samsung SCH-I829 Galaxy Style Duos

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140417%26_u.date01%3D20140417/

Thread: main, Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41c15ab0 is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:712)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:356)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:234)
 at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:153)
 at android.view.Window$LocalWindowManager.addView(Window.java:557)
 at android.app.Dialog.show(Dialog.java:277)
 at com.lw1a2.myeslpod.cq.c(Unknown Source)
 at com.lw1a2.myeslpod.cq.d(Unknown Source)
 at com.lw1a2.myeslpod.cr.run(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4963)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41c15ab0 is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:712)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:356)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:234)
 at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:153)
 at android.view.Window$LocalWindowManager.addView(Window.java:557)
 at android.app.Dialog.show(Dialog.java:277)
 at com.lw1a2.myeslpod.Upgrade.show(Unknown Source)
                               access$3
                               access$15
 at com.lw1a2.myeslpod.Upgrade.downloadApk(Unknown Source)
                               access$4
 at com.lw1a2.myeslpod.Upgrade$1.run(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4963)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
http://stackoverflow.com/questions/18662239/android-view-windowmanagerbadtokenexception-unable-to-add-window-on-buider-s

**Comment by lw1a2** [comment]
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140505%26_u.date01%3D20140505%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.appVersion/

version: 1.5.1c
Thread: main, Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41ac50e8 is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:576)
 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:246)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
 at android.app.Dialog.show(Dialog.java:290)
 at com.lw1a2.myeslpod.bn.c(Unknown Source)
 at com.lw1a2.myeslpod.bn.d(Unknown Source)
 at com.lw1a2.myeslpod.bo.run(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5068)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41ac50e8 is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:576)
 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:246)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
 at android.app.Dialog.show(Dialog.java:290)
 at com.lw1a2.myeslpod.Upgrade.show(Unknown Source)
                               access$3
 at com.lw1a2.myeslpod.Upgrade.downloadApk(Unknown Source)
                               access$4
 at com.lw1a2.myeslpod.Upgrade$1.run(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5068)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140505%26_u.date01%3D20140505%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.appVersion/

version: 1.7.2c

Thread: main, Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41ab5068 is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:712)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:356)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:234)
 at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:153)
 at android.view.Window$LocalWindowManager.addView(Window.java:557)
 at android.app.Dialog.show(Dialog.java:277)
 at com.lw1a2.myeslpod.cx.c(Unknown Source)
 at com.lw1a2.myeslpod.cx.d(Unknown Source)
 at com.lw1a2.myeslpod.cy.run(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4963)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@41ab5068 is not valid; is your activity running?
 at android.view.ViewRootImpl.setView(ViewRootImpl.java:712)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:356)
 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:234)
 at android.view.WindowManagerImpl$CompatModeWrapper.addView(WindowManagerImpl.java:153)
 at android.view.Window$LocalWindowManager.addView(Window.java:557)
 at android.app.Dialog.show(Dialog.java:277)
 at com.lw1a2.myeslpod.Upgrade.show(Unknown Source)
                               access$3
                               access$15
 at com.lw1a2.myeslpod.Upgrade.downloadApk(Unknown Source)
                               access$4
 at com.lw1a2.myeslpod.Upgrade$1.run(Unknown Source)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4963)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
fixed at 1.8.1c
