### ISSUE TITLE
 java.lang.IllegalArgumentException: Invalid payload item type

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#154]
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140429%26_u.date01%3D20140429%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.operatingSystemVersion%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription/

Thread: main, Exception: java.lang.IllegalArgumentException: Invalid payload item type
 at android.util.EventLog.writeEvent(Native Method)
 at android.app.Activity.onMenuItemSelected(Activity.java:2611)
 at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1141)
 at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
 at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
 at com.android.internal.view.menu.ListMenuPresenter.onItemClick(ListMenuPresenter.java:178)
 at android.widget.AdapterView.performItemClick(AdapterView.java:301)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1508)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3293)
 at android.widget.AbsListView$1.run(AbsListView.java:4554)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:5365)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.IllegalArgumentException: Invalid payload item type
 at android.util.EventLog.writeEvent(Native Method)
 at android.app.Activity.onMenuItemSelected(Activity.java:2610)
 at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1060)
 at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
 at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
 at com.android.internal.view.menu.ListMenuPresenter.onItemClick(ListMenuPresenter.java:180)
 at android.widget.AdapterView.performItemClick(AdapterView.java:301)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1287)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3080)
 at android.widget.AbsListView$1.run(AbsListView.java:4161)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4944)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.IllegalArgumentException: Invalid payload item type
 at android.util.EventLog.writeEvent(Native Method)
 at android.app.Activity.onMenuItemSelected(Activity.java:2611)
 at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1141)
 at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
 at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
 at com.android.internal.view.menu.ListMenuPresenter.onItemClick(ListMenuPresenter.java:178)
 at android.widget.AdapterView.performItemClick(AdapterView.java:301)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1507)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3292)
 at android.widget.AbsListView$1.run(AbsListView.java:4545)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:5299)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.IllegalArgumentException: Invalid payload item type
 at android.util.EventLog.writeEvent(Native Method)
 at android.app.Activity.onMenuItemSelected(Activity.java:2611)
 at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1141)
 at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:735)
 at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:149)
 at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
 at com.android.internal.view.menu.ListMenuPresenter.onItemClick(ListMenuPresenter.java:178)
 at android.widget.AdapterView.performItemClick(AdapterView.java:301)
 at android.widget.AbsListView.performItemClick(AbsListView.java:1508)
 at android.widget.AbsListView$PerformClick.run(AbsListView.java:3293)
 at android.widget.AbsListView$1.run(AbsListView.java:4554)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:176)
 at android.app.ActivityThread.main(ActivityThread.java:5319)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1108)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
in public boolean onMenuItemSelected(int featureId, MenuItem item), it should be check titleCondensed before invoking EventLog.writeEvent:
if(titleCondensed != null) {
    EventLog.writeEvent(50000, 0, titleCondensed.toString());
}

It has already fixed in android 4.4.2.
Here use workaround
