### ISSUE TITLE
 java.lang.IndexOutOfBoundsException  at android.graphics.Paint.getTextRunAdvances

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#163]
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140515%26_u.date01%3D20140515%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

version: 1.8.1c
os: 4.1.2
moblie: Coolpad 5950

Thread: main, Exception: java.lang.IndexOutOfBoundsException
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1731)
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1704)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
 at android.text.StaticLayout.generate(StaticLayout.java:281)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
 at android.text.DynamicLayout.<init>(DynamicLayout.java:170)
 at android.widget.TextView.makeSingleLayout(TextView.java:5853)
 at android.widget.TextView.makeNewLayout(TextView.java:5751)
 at android.widget.TextView.onMeasure(TextView.java:6108)
 at android.view.View.measure(View.java:15172)
 at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1196)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.widget.ScrollView.onMeasure(ScrollView.java:318)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2148)
 at android.view.View.measure(View.java:15172)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1848)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1100)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1273)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
 at android.view.Choreographer.doCallbacks(Choreographer.java:555)
 at android.view.Choreographer.doFrame(Choreographer.java:525)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4823)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.IndexOutOfBoundsException
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1731)
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1704)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
 at android.text.StaticLayout.generate(StaticLayout.java:281)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
 at android.text.DynamicLayout.<init>(DynamicLayout.java:170)
 at android.widget.TextView.makeSingleLayout(TextView.java:5853)
 at android.widget.TextView.makeNewLayout(TextView.java:5751)
 at android.widget.TextView.onMeasure(TextView.java:6108)
 at android.view.View.measure(View.java:15172)
 at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1196)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.widget.ScrollView.onMeasure(ScrollView.java:318)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.view.View.measure(View.java:15172)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15172)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2148)
 at android.view.View.measure(View.java:15172)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1848)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1100)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1273)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
 at android.view.Choreographer.doCallbacks(Choreographer.java:555)
 at android.view.Choreographer.doFrame(Choreographer.java:525)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4823)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
 at dalvik.system.NativeStart.main(Native Method)

version: 1.8.1c
os: 4.1.2
moblie: Samsung GT-I9268 Galaxy Premier

Thread: main, Exception: java.lang.IndexOutOfBoundsException
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1774)
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1747)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
 at android.text.StaticLayout.generate(StaticLayout.java:281)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:332)
 at android.text.DynamicLayout.<init>(DynamicLayout.java:176)
 at android.widget.TextView.makeSingleLayout(TextView.java:6166)
 at android.widget.TextView.makeNewLayout(TextView.java:6064)
 at android.widget.TextView.assumeLayout(TextView.java:5949)
 at android.widget.TextView.onPreDraw(TextView.java:4621)
 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:703)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1941)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4474)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
 at android.view.Choreographer.doCallbacks(Choreographer.java:555)
 at android.view.Choreographer.doFrame(Choreographer.java:525)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4918)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.IndexOutOfBoundsException
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1774)
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1747)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
 at android.text.StaticLayout.generate(StaticLayout.java:281)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:332)
 at android.text.DynamicLayout.<init>(DynamicLayout.java:176)
 at android.widget.TextView.makeSingleLayout(TextView.java:6166)
 at android.widget.TextView.makeNewLayout(TextView.java:6064)
 at android.widget.TextView.assumeLayout(TextView.java:5949)
 at android.widget.TextView.onPreDraw(TextView.java:4621)
 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:703)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1941)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4474)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
 at android.view.Choreographer.doCallbacks(Choreographer.java:555)
 at android.view.Choreographer.doFrame(Choreographer.java:525)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4918)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:994)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:761)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
version: 1.8.1c
os: 4.1.1
mobile: Huawei U9500

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140518%26_u.date01%3D20140518%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: main, Exception: java.lang.IndexOutOfBoundsException
 at android.graphics.Paint.getTextRunAdvances(Paint.java)
 at android.graphics.Paint.getTextRunAdvances(Paint.java)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java)
 at android.text.StaticLayout.generate(StaticLayout.java)
 at android.text.DynamicLayout.reflow(DynamicLayout.java)
 at android.text.DynamicLayout.<init>(DynamicLayout.java)
 at android.widget.TextView.makeSingleLayout(TextView.java)
 at android.widget.TextView.makeNewLayout(TextView.java)
 at android.widget.TextView.assumeLayout(TextView.java)
 at android.widget.TextView.onPreDraw(TextView.java)
 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
 at android.view.Choreographer.doCallbacks(Choreographer.java)
 at android.view.Choreographer.doFrame(Choreographer.java)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
 at android.os.Handler.handleCallback(Handler.java)
 at android.os.Handler.dispatchMessage(Handler.java)
 at android.os.Looper.loop(Looper.java)
 at android.app.ActivityThread.main(ActivityThread.java)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140530%26_u.date01%3D20140603%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.operatingSystemVersion%26_r.drilldown%3Danalytics.appVersion%3A1.8.1c/

**Comment by lw1a2** [comment]
version: 1.8.3c
os: 4.1.1
mobile: (not set)

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140613%26_u.date01%3D20140618%26explorer-table.plotKeys%3D[]%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription/

Thread: main, Exception: java.lang.IndexOutOfBoundsException
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1731)
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1704)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
 at android.text.StaticLayout.generate(StaticLayout.java:281)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
 at android.text.DynamicLayout.<init>(DynamicLayout.java:170)
 at android.widget.TextView.makeSingleLayout(TextView.java:5843)
 at android.widget.TextView.makeNewLayout(TextView.java:5741)
 at android.widget.TextView.onMeasure(TextView.java:6098)
 at android.view.View.measure(View.java:15190)
 at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1196)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.widget.ScrollView.onMeasure(ScrollView.java:318)
 at android.view.View.measure(View.java:15190)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15190)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15190)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15190)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at android.view.View.measure(View.java:15190)
 at android.widget.LinearLayout.measureVertical(LinearLayout.java:833)
 at android.widget.LinearLayout.onMeasure(LinearLayout.java:574)
 at android.view.View.measure(View.java:15190)
 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4814)
 at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
 at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2148)
 at android.view.View.measure(View.java:15190)
 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1848)
 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1100)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1273)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:998)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4212)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
 at android.view.Choreographer.doCallbacks(Choreographer.java:555)
 at android.view.Choreographer.doFrame(Choreographer.java:525)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4745)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
It happened again.

ver: 1.9c
os: 4.1.1
mobile: AMOI N821

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140628%26_u.date01%3D20140629%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D[]%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: main, Exception: java.lang.IndexOutOfBoundsException
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1731)
 at android.graphics.Paint.getTextRunAdvances(Paint.java:1704)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:164)
 at android.text.MeasuredText.addStyleRun(MeasuredText.java:204)
 at android.text.StaticLayout.generate(StaticLayout.java:281)
 at android.text.DynamicLayout.reflow(DynamicLayout.java:284)
 at android.text.DynamicLayout.<init>(DynamicLayout.java:170)
 at android.widget.TextView.makeSingleLayout(TextView.java:5863)
 at android.widget.TextView.makeNewLayout(TextView.java:5761)
 at android.widget.TextView.assumeLayout(TextView.java:5653)
 at android.widget.TextView.onPreDraw(TextView.java:4412)
 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:726)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2084)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1125)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4607)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:747)
 at android.view.Choreographer.doCallbacks(Choreographer.java:567)
 at android.view.Choreographer.doFrame(Choreographer.java:536)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:733)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:153)
 at android.app.ActivityThread.main(ActivityThread.java:5086)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
Override onPreDraw to handle exception
