### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#165]
version: 1.8.1c
os: 4.1.1
mobile: Meizu M032 MX

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140517%26_u.date01%3D20140517%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: main, Exception: java.lang.ExceptionInInitializerError
 at com.lw1a2.myeslpod.cx.b(Unknown Source)
 at com.lw1a2.myeslpod.bh.onReceive(Unknown Source)
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:762)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4866)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.NullPointerException
 at com.lw1a2.myeslpod.ar.<clinit>(Unknown Source) ... 12 more

Thread: main, Exception: java.lang.ExceptionInInitializerError
 at com.lw1a2.myeslpod.Util.removeActivity(Unknown Source)
                            exitApp
                            processTitle
                            getBingURL
 at com.lw1a2.myeslpod.MyNotification$1.onReceive(Unknown Source)
 at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:762)
 at android.os.Handler.handleCallback(Handler.java:615)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4866)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.NullPointerException
 at com.lw1a2.myeslpod.ar.<clinit>(Unknown Source) ... 12 more

**Comment by lw1a2** [comment]
It is casued by initialization of com.lw1a2.myeslpod.Listened
