### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#169]
version: 1.8.2c
os: 4.2.2
moblie: ZTE NX403A Nubia Z5S

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140522%26_u.date01%3D20140522%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: main, Exception: java.lang.NoSuchFieldError: android.content.pm.ResolveInfo.icon
 at android.content.pm.ResolveInfo.loadIcon(ResolveInfo.java:180)
 at android.widget.ActivityChooserView$ActivityChooserViewAdapter.getView(ActivityChooserView.java:712)
 at android.widget.ActivityChooserView$ActivityChooserViewAdapter.measureContentWidth(ActivityChooserView.java:742)
 at android.widget.ActivityChooserView.showPopupUnchecked(ActivityChooserView.java:346)
 at android.widget.ActivityChooserView.access$500(ActivityChooserView.java:61)
 at android.widget.ActivityChooserView$Callbacks.onClick(ActivityChooserView.java:572)
 at android.view.View.performClick(View.java:4204)
 at android.view.View$PerformClick.run(View.java:17355)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5102)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
 at dalvik.system.NativeStart.main(Native Method)

Thread: main, Exception: java.lang.NoSuchFieldError: android.content.pm.ResolveInfo.icon
 at android.content.pm.ResolveInfo.loadIcon(ResolveInfo.java:180)
 at android.widget.ActivityChooserView$ActivityChooserViewAdapter.getView(ActivityChooserView.java:712)
 at android.widget.ActivityChooserView$ActivityChooserViewAdapter.measureContentWidth(ActivityChooserView.java:742)
 at android.widget.ActivityChooserView.showPopupUnchecked(ActivityChooserView.java:346)
 at android.widget.ActivityChooserView.access$500(ActivityChooserView.java:61)
 at android.widget.ActivityChooserView$Callbacks.onClick(ActivityChooserView.java:572)
 at android.view.View.performClick(View.java:4204)
 at android.view.View$PerformClick.run(View.java:17355)
 at android.os.Handler.handleCallback(Handler.java:725)
 at android.os.Handler.dispatchMessage(Handler.java:92)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:5102)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
version: 1.10.1c
os: 4.2.2
moblie: ZTE NX403A Nubia Z5S

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140729%26_u.date01%3D20140730%26explorer-table.plotKeys%3D[]%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo%26_r.drilldown%3Danalytics.appVersion%3A1.10.1c/

**Comment by lw1a2** [comment]
It happened in 1.10.2c again

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140822%26_u.date01%3D20140824%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D[]/
