### ISSUE TITLE
java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(2131165212, class android.widget.ListView) with Adapter(class com.lw1a2.myeslpod.EpisodeAdapter)

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#178]
there is a exception for notListened listview in Challenge

06-28 00:09:41.553: E/AndroidRuntime(553): FATAL EXCEPTION: main
06-28 00:09:41.553: E/AndroidRuntime(553): java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(2131165212, class android.widget.ListView) with Adapter(class com.lw1a2.myeslpod.EpisodeAdapter)]
06-28 00:09:41.553: E/AndroidRuntime(553):  at android.widget.ListView.layoutChildren(ListView.java:1510)
06-28 00:09:41.553: E/AndroidRuntime(553):  at android.widget.AbsListView$CheckForTap.run(AbsListView.java:2000)
06-28 00:09:41.553: E/AndroidRuntime(553):  at android.os.Handler.handleCallback(Handler.java:587)
06-28 00:09:41.553: E/AndroidRuntime(553):  at android.os.Handler.dispatchMessage(Handler.java:92)
06-28 00:09:41.553: E/AndroidRuntime(553):  at android.os.Looper.loop(Looper.java:123)
06-28 00:09:41.553: E/AndroidRuntime(553):  at android.app.ActivityThread.main(ActivityThread.java:3683)
06-28 00:09:41.553: E/AndroidRuntime(553):  at java.lang.reflect.Method.invokeNative(Native Method)
06-28 00:09:41.553: E/AndroidRuntime(553):  at java.lang.reflect.Method.invoke(Method.java:507)
06-28 00:09:41.553: E/AndroidRuntime(553):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
06-28 00:09:41.553: E/AndroidRuntime(553):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
06-28 00:09:41.553: E/AndroidRuntime(553):  at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
Thread: main, Exception: java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. [in ListView(2131165212, class android.widget.ListView) with Adapter(class com.lw1a2.myeslpod.ae)] at android.widget.ListView.layoutChildren(ListView.java:1557) at android.widget.AbsListView.onTouchEvent(AbsListView.java:4598) at android.view.View.dispatchTouchEvent(View.java:7817) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2435) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2441) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2174) at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2326) at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1612) at android.app.Activity.dispatchTouchEvent(Activity.java:2494) at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2274) at android.view.View.dispatchPointerEvent(View.java:8025) at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4668) at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4556) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176) at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4261) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184) at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4318) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4207) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4176) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4184) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4150) at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6302) at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6240) at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6211) at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6382) at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188) at android.os.MessageQueue.nativePollOnce(Native Method) at android.os.MessageQueue.next(MessageQueue.java:132) at android.os.Looper.loop(Looper.java:138) at android.app.ActivityThread.main(ActivityThread.java:5419) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:525) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025) at dalvik.system.NativeStart.main(Native Method)
