### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException at com.lw1a2.myeslpod.Download$DownloadMp3.downloadMp3Impl

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#207]
version: 1.9c
os: 4.4.2
mobile: Samsung SM-N900T Galaxy Note 3

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140806%26_u.date01%3D20140806%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D[]%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: Thread-1082, Exception: java.lang.ArrayIndexOutOfBoundsException: length=1024; regionStart=0; regionLength=-2765130
 at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
 at java.io.BufferedInputStream.read(BufferedInputStream.java:252)
 at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:527)
 at java.io.InputStream.read(InputStream.java:162)
 at com.lw1a2.myeslpod.Download$DownloadMp3.downloadMp3Impl(Unknown Source)
 at com.lw1a2.myeslpod.Download$DownloadMp3.run(Unknown Source)

**Comment by lw1a2** [comment]
version: 1.10.2c
os: 4.4.2
mobile: Samsung SM-N9005 Galaxy Note 3

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20140808%26_u.date01%3D20140811%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D[]%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: Thread-3400, Exception: java.lang.ArrayIndexOutOfBoundsException: length=1024; regionStart=0; regionLength=-2765130
 at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
 at java.io.BufferedInputStream.read(BufferedInputStream.java:252)
 at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:527)
 at java.io.InputStream.read(InputStream.java:162)
 at com.lw1a2.myeslpod.Download$DownloadMp3.downloadMp3Impl(Unknown Source)
 at com.lw1a2.myeslpod.Download$DownloadMp3.run(Unknown Source)
