### ISSUE TITLE
 java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#236]
ver: 1.12c
mobile: Motorola XT1060 Moto X

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20141027%26_u.date01%3D20141027%26explorer-segmentExplorer.segmentId%3Danalytics.exceptionDescription%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.mobileDeviceInfo/

Thread: Thread-699, Exception: java.lang.OutOfMemoryError: Failed to allocate a 1112588 byte allocation with 4912360 free bytes
 at android.graphics.Bitmap.nativeCreate(Native Method)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:908)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:932)
 at org.vudroid.pdfdroid.codec.PdfPage.getWidth(Unknown Source)
                                       renderBitmap
                                       createPage
                                       render
 at org.vudroid.pdfdroid.codec.PdfPage.getWidth(Unknown Source)
                                       renderBitmap
                                       createPage
                                       render
 at com.lw1a2.myeslpod.pdf.Pdf$1.run(Unknown Source)

**Comment by lw1a2** [comment]
android:largeHeap="true"

**Comment by lw1a2** [comment]
Thread: Thread-74, Exception: java.lang.OutOfMemoryError: (Heap Size=32007KB, Allocated=16700KB, Bitmap Size=67KB)
 at com.lw1a2.myeslpod.SliceDownload.setUpdateBufferUI(Unknown Source)
                                     downloadMp3Impl
                                     notifyToPlay
                                     getMp3Size
 at com.lw1a2.myeslpod.SliceDownload.run(Unknown Source)

**Comment by lw1a2** [comment]
how to handle 16m heap?

**Comment by lw1a2** [comment]
The issue of loading episode is fixed.
The issue of loading episode won't be fixed.
