### ISSUE TITLE
java.lang.IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#239]
ver: 1.12
os: 4.4.2
mobile: Samsung GT-I9505 Galaxy S IV

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20141029%26_u.date01%3D20141112%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.operatingSystemVersion%26_r.drilldown%3Danalytics.appVersion%3A1.12/

Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lw1a2.myeslpod/com.lw1a2.myeslpod.MainActivity}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
 at android.app.ActivityThread.access$900(ActivityThread.java:161)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:157)
 at android.app.ActivityThread.main(ActivityThread.java:5356)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
 at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.util.TimSort.mergeHi(TimSort.java:864)
 at java.util.TimSort.mergeAt(TimSort.java:481)
 at java.util.TimSort.mergeCollapse(TimSort.java:404)
 at java.util.TimSort.sort(TimSort.java:210)
 at java.util.TimSort.sort(TimSort.java:169)
 at java.util.Arrays.sort(Arrays.java:2023)
 at java.util.Collections.sort(Collections.java:1883)
 at com.lw1a2.myeslpod.Local.initEpisodes(Unknown Source)
 at com.lw1a2.myeslpod.Local.<init>(Unknown Source)
 at com.lw1a2.myeslpod.MainActivity.onCreate(Unknown Source)
 at android.app.Activity.performCreate(Activity.java:5426)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269) ... 11 more

**Comment by lw1a2** [comment]
ver: 1.12
os: 4.4.2
mobile: Samsung GT-I9505 Galaxy S IV

https://www.google.com/analytics/web/#report/app-content-crashes/a46283877w77245857p80654704/%3F_u.date00%3D20141029%26_u.date01%3D20141112%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.operatingSystemVersion%26_r.drilldown%3Danalytics.appVersion%3A1.12/

Thread: main, Exception: java.lang.RuntimeException: Unable to stop activity {com.lw1a2.myeslpod/com.lw1a2.myeslpod.activity.Settings}: java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3647)
 at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3701)
 at android.app.ActivityThread.access$1500(ActivityThread.java:161)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:157)
 at android.app.ActivityThread.main(ActivityThread.java:5356)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:515)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
 at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.util.TimSort.mergeHi(TimSort.java:864)
 at java.util.TimSort.mergeAt(TimSort.java:481)
 at java.util.TimSort.mergeCollapse(TimSort.java:404)
 at java.util.TimSort.sort(TimSort.java:210)
 at java.util.TimSort.sort(TimSort.java:169)
 at java.util.Arrays.sort(Arrays.java:2023)
 at java.util.Collections.sort(Collections.java:1883)
 at com.lw1a2.myeslpod.Local.initEpisodes(Unknown Source)
 at com.lw1a2.myeslpod.MainActivity.reloadLocalNDownload(Unknown Source)
 at com.lw1a2.myeslpod.activity.Settings.onStop(Unknown Source)
 at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1230)
 at android.app.Activity.performStop(Activity.java:5571)
 at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3642) ... 11 more
