### ISSUE TITLE
ANR: play next episode which doesn't exist in mobile cause ANR

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#69]
stack trace maybe like this:

Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lw1a2.myeslpod/com.lw1a2.myeslpod.Detail}: java.lang.NullPointerException at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135) at android.app.ActivityThread.access$700(ActivityThread.java:140) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1237) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:137) at android.app.ActivityThread.main(ActivityThread.java:4921) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.NullPointerException at com.lw1a2.myeslpod.Detail.onCreate(Unknown Source) at android.app.Activity.performCreate(Activity.java:5188) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074) ... 11 more

or:
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lw1a2.myeslpod/com.lw1a2.myeslpod.OnlineDetail}: java.lang.NullPointerException at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2081) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106) at android.app.ActivityThread.access$600(ActivityThread.java:138) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1204) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:137) at android.app.ActivityThread.main(ActivityThread.java:4929) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557) at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.NullPointerException at com.lw1a2.myeslpod.Detail.onCreate(Unknown Source) at com.lw1a2.myeslpod.OnlineDetail.onCreate(Unknown Source) at android.app.Activity.performCreate(Activity.java:5244) at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082) at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045) ... 11 more

**Comment by lw1a2** [comment]
Stack trace is reported by GA.
I do not definitely make sure stack trace cause by this issue.
But I played next episode which doesn't exist in mobile, its stack trace is very similar with GA's.

**Comment by lw1a2** [comment]
check shareActionProvider before use it

**Comment by lw1a2** [comment]
The issue happened again, so the stack trace isn't caused by it.
I'll create a new issue to track it.
