### ISSUE TITLE
ANR: getSystemService(Context.DOWNLOAD_SERVICE) return null

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#71]
mobile: Huawei P6-U06 Ascend P6
os: 4.2.2

stack trace:
Thread: main, Exception: java.lang.NullPointerException
at android.app.DownloadManager.enqueue(DownloadManager.java)
at com.lw1a2.myeslpod.ay.d(Unknown Source)
at com.lw1a2.myeslpod.ay.j(Unknown Source)
at com.lw1a2.myeslpod.bb.onClick(Unknown Source)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java)
at android.os.Handler.dispatchMessage(Handler.java)
at android.os.Looper.loop(Looper.java)
at android.app.ActivityThread.main(ActivityThread.java)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
check it is null or not before using it
