### ISSUE TITLE
ANR:  Unable to start activity ComponentInfo{com.lw1a2.myeslpod/com.lw1a2.myeslpod.OnlineDetail}

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#72]
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lw1a2.myeslpod/com.lw1a2.myeslpod.OnlineDetail}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2460)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2521)
at android.app.ActivityThread.access$600(ActivityThread.java:162)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:5777)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.NullPointerException
at com.lw1a2.myeslpod.Detail.onCreate(Unknown Source)
at com.lw1a2.myeslpod.OnlineDetail.onCreate(Unknown Source)
at android.app.Activity.performCreate(Activity.java:5165)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1103)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416) ... 11 more

**Comment by lw1a2** [comment]
It reoccur:

version: 1.4.4
stack:
01-10 09:05:56.790: E/AndroidRuntime(28735): FATAL EXCEPTION: main
01-10 09:05:56.790: E/AndroidRuntime(28735): Process: com.lw1a2.myeslpod, PID: 28735
01-10 09:05:56.790: E/AndroidRuntime(28735): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lw1a2.myeslpod/com.lw1a2.myeslpod.Detail}: java.lang.NullPointerException
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.ActivityThread.access$800(ActivityThread.java:135)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.os.Handler.dispatchMessage(Handler.java:102)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.os.Looper.loop(Looper.java:136)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.ActivityThread.main(ActivityThread.java:5017)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at java.lang.reflect.Method.invokeNative(Native Method)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at java.lang.reflect.Method.invoke(Method.java:515)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at dalvik.system.NativeStart.main(Native Method)
01-10 09:05:56.790: E/AndroidRuntime(28735): Caused by: java.lang.NullPointerException
01-10 09:05:56.790: E/AndroidRuntime(28735):    at com.lw1a2.myeslpod.Detail.onCreate(Detail.java:116)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.Activity.performCreate(Activity.java:5231)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
01-10 09:05:56.790: E/AndroidRuntime(28735):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
01-10 09:05:56.790: E/AndroidRuntime(28735):    ... 11 more

**Comment by lw1a2** [comment]
reoccur step:
1. click a episode
2. return main
3. click notification

**Comment by lw1a2** [comment]
reoccur in 1.4.5:
Thread: main, Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lw1a2.myeslpod/com.lw1a2.myeslpod.OnlineDetail}: java.lang.NullPointerException
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1696)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1716)
 at android.app.ActivityThread.access$1500(ActivityThread.java:124)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:968)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:130)
 at android.app.ActivityThread.main(ActivityThread.java:3806)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:507)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
 at dalvik.system.NativeStart.main(Native Method) Caused by: java.lang.NullPointerException
 at com.lw1a2.myeslpod.Detail.onCreate(Unknown Source)
 at com.lw1a2.myeslpod.OnlineDetail.onCreate(Unknown Source)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1660) ... 11 more
