### ISSUE TITLE
ANR: download cause ANR

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#78]
version: 1.4.3c
os: 4.1.2
mobile: Samsung GT-N7102 Galaxy Note II

stack:
Thread: main, Exception: java.lang.IllegalArgumentException: Unknown URL content://downloads/my_downloads
 at android.content.ContentResolver.insert(ContentResolver.java:862)
 at android.app.DownloadManager.enqueue(DownloadManager.java:1252)
 at com.lw1a2.myeslpod.ay.d(Unknown Source)
 at com.lw1a2.myeslpod.ay.j(Unknown Source)
 at com.lw1a2.myeslpod.bb.onClick(Unknown Source)
 at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:137)
 at android.app.ActivityThread.main(ActivityThread.java:4921)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:511)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1008)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:775)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by lw1a2** [comment]
Download Manager app is disabled cause this issue.
Ref: http://stackoverflow.com/questions/18979160/android-download-manager-issue-in-samsung-tab-gt-p3100
