### ISSUE TITLE
ARN: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lw1a2** [MyEslPod/TODO#82]
1.4.3c

Thread: Thread-13, Exception: java.lang.ArrayIndexOutOfBoundsException
 at java.util.ArrayList.remove(ArrayList.java:408)
 at java.security.AccessController.doPrivileged(AccessController.java:118)
 at java.security.AccessController.doPrivileged(AccessController.java:85)
 at java.net.ProxySelectorImpl.getSystemProperty(ProxySelectorImpl.java:297)
 at java.net.ProxySelectorImpl.getSystemProperty(ProxySelectorImpl.java:288)
 at java.net.ProxySelectorImpl.selectHttpProxy(ProxySelectorImpl.java:128)
 at java.net.ProxySelectorImpl.select(ProxySelectorImpl.java:96)
 at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.makeConnection(HttpURLConnectionImpl.java:257)
 at org.apache.harmony.luni.internal.net.www.protocol.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:214)
 at com.lw1a2.myeslpod.t.a(Unknown Source)
 at com.lw1a2.myeslpod.t.run(Unknown Source)

**Comment by lw1a2** [comment]
Not reproduce
